import React, { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, ChevronRight, CircleCheck, Clock3, FileCheck2, Info, LockKeyhole, ShieldCheck, Wallet, X } from 'lucide-react';
import { useApp } from './App.jsx';
import { money, number, programs, shortAddress } from './data.js';
import { Badge, Button, UsdcIcon, DataRow, InlineLink, Notice, PageHeading, Progress, RuleList, SectionHeading, SessionNotice, Steps, WalletOptions } from './ui.jsx';

function ProgramPicker() { const { program, setProgramSize } = useApp(); return <div className="program-picker" role="group" aria-label="Choose account size">{programs.map(p => <button key={p.size} aria-pressed={program.size === p.size} className={program.size === p.size ? 'active' : ''} onClick={() => setProgramSize(p.size)}>${p.name}</button>)}</div>; }
function FeeSummary({ total = true }) { const { program } = useApp(); return <><DataRow label="Evaluation fee" value={`${number(program.fee)} USDC`} /><DataRow label="Estimated network fee" value="0.02 USDC" />{total && <DataRow className="total" label="Total due" value={`${number(program.fee + .02)} USDC`} />}</>; }

export function FundingPage() {
  const { program, navigate } = useApp();
  return <div className="page funding-page"><Steps active={1} /><div className="funding-layout"><section className="funding-story"><h1>Your edge.<br /><span>More capital.</span></h1><p className="funding-intro">Show what you can do. Pass an evaluation, trade a funded account, and keep 80% of your profits.</p><div className="funding-journey">{[['Prove your process', 'Trade a simulated account with clear, visible rules.'], ['Step into funded trading', 'Put your strategy to work with allocated capital.'], ['Keep your share', 'Request eligible profits in USDC. Follow every record.']].map(([title, text], i) => <div key={title}><span>{i + 1}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="funding-bottom"><ShieldCheck size={18} /><span>Built for clarity. From your first trade to your payout.</span></div><a href="#/trade/practice" className="practice-link">Get a feel for the platform first <ArrowUpRight size={15} /></a></section><section className="program-sheet"><div className="program-sheet-title"><h2>Start your evaluation</h2><Badge tone="purple">One step</Badge></div><p>Choose your starting account size.</p><ProgramPicker /><div className="program-face"><span>Evaluation balance</span><strong>{money(program.size, 0)}</strong><span className="program-face-note">Virtual capital · Real opportunity</span></div><RuleList size={program.size} /><div className="program-price"><span>One-time evaluation fee<small>Illustrative program pricing</small></span><strong>{money(program.fee, 0)}<span> USDC</span></strong></div><Button className="full-width" icon={ArrowRight} onClick={() => navigate('/program')}>Choose {program.name} account</Button><p className="sheet-footnote">Review all rules and costs before paying.</p></section></div><div className="funding-market-line"><span>One workspace. More ways to trade.</span><strong>Crypto</strong><i /><strong>Gold</strong><i /><strong>Forex</strong><i /><strong>Stocks</strong><Badge>Perpetual contracts</Badge></div></div>;
}

export function ProgramPage() {
  const { program, navigate } = useApp();
  const [open, setOpen] = useState('drawdown');
  const details = [
    ['target', 'How is the profit target calculated?', `Reach ${money(program.size * .08)} in qualifying net profit. The example includes trading costs and checks the account result before marking the evaluation passed.`],
    ['drawdown', 'How does the drawdown limit work?', `This example uses a static equity floor of ${money(program.size * .95)}. Open P&L and trading costs count toward equity. Gains do not move this floor upward.`],
    ['capital', 'What changes after I pass?', 'The account moves through funded activation. Once capital and permissions are ready, trades can use the proposed GMTrade integration. Evaluation profits are not withdrawable.'],
    ['payout', 'When can I request a payout?', 'The design shows an 80% share of eligible, settled funded profits. Final minimums, settlement rules and the effect of payouts on an account are product decisions still to be set.'],
  ];
  return <div className="page"><Steps active={1} /><PageHeading title="Know the rules. Own your process." description="A clear agreement before your first trade." back={{ label: 'Choose an account', href: '#/get-funded' }}><Badge tone="purple">Illustrative rules · v0.1</Badge></PageHeading><div className="checkout-layout"><section><div className="surface rules-main"><SectionHeading>Evaluation terms</SectionHeading><RuleList size={program.size} /><DataRow label="Maximum leverage" value="10×, subject to market limits" /><DataRow label="Trading environment" value="Simulated evaluation" /><DataRow label="Payment currency" value="USDC on Solana" /></div><section className="rules-explained"><h2>A few details worth understanding.</h2>{details.map(([id, title, text]) => <div className={`accordion ${open === id ? 'open' : ''}`} key={id}><button aria-expanded={open === id} onClick={() => setOpen(open === id ? null : id)}>{title}<ChevronDown size={16} /></button>{open === id && <p>{text}</p>}</div>)}</section></section><aside className="purchase-summary"><div className="purchase-summary-top"><img src="/brand/symbol.svg" alt="" /><Badge>Evaluation</Badge><h2>{program.name} account</h2><p>One clear step toward funded trading.</p></div><div className="purchase-summary-body"><FeeSummary /><Button className="full-width" icon={ArrowRight} onClick={() => navigate('/connect')}>Continue with this account</Button><div className="fine-print"><ShieldCheck size={14} /><span>You will review the total again before the preview payment.</span></div></div><Notice>All program settings here are illustrative. They are not a live commercial offer.</Notice></aside></div></div>;
}

export function ConnectPage() {
  const { program, session, navigate } = useApp();
  const [chosen, setChosen] = useState(false);
  useEffect(() => { if (chosen && session.status === 'signed-in') navigate('/checkout'); }, [chosen, session.status, navigate]);
  function choose(name) { setChosen(true); session.connect(name); }
  const usdc = session.me?.usdcBalance;
  return <div className="page connection-page"><Steps active={2} /><div className="connection-layout"><section><div className="wallet-outline"><Wallet size={34} strokeWidth={1.35} /></div><h1>Your account starts<br />with your wallet.</h1><p>One connection for your evaluation, funded account and future USDC payouts.</p><div className="connection-points"><div><Check size={15} /><span>USDC on Solana</span></div><div><Check size={15} /><span>Review every action before signing</span></div><div><Check size={15} /><span>Your identity across every account stage</span></div></div><InlineLink href="#/program">Back to program details</InlineLink></section><section className="surface connect-sheet"><h2>Connect a wallet</h2><p>Pick a Solana wallet, then sign a message to prove it's yours.</p><WalletOptions session={session} onChoose={choose} /><div className="connect-balance"><DataRow label="USDC balance" value={session.status !== 'signed-in' ? 'Sign in to view' : usdc == null ? 'Unavailable' : `${number(Number(usdc))} USDC`} /><DataRow label="Selected evaluation" value={`${program.name} account`} /><DataRow label="Estimated total" value={`${number(program.fee + .02)} USDC`} /></div><SessionNotice session={session}>Signing in sends no transaction and costs nothing. You approve every payment separately in your wallet.</SessionNotice><div className="connect-privacy"><LockKeyhole size={13} /><span>Wallet connection never requires a recovery phrase.</span></div></section></div></div>;
}

export function CheckoutPage() {
  const { program, session, navigate } = useApp();
  const [accepted, setAccepted] = useState(false);
  const [busy, setBusy] = useState(false);
  function pay() { if (!accepted) return; setBusy(true); sessionStorage.setItem('props.payment', 'pending'); window.setTimeout(() => navigate('/payment'), 450); }
  const usdc = session.status === 'signed-in' ? session.me.usdcBalance : null;
  const covered = usdc != null && Number(usdc) >= program.fee + .02;
  return <div className="page checkout-page"><Steps active={3} /><PageHeading title="One last look. Then you're in." description="Review your evaluation and the exact amount before continuing." back={{ label: 'Wallet connection', href: '#/connect' }} /><div className="checkout-layout"><section className="surface checkout-details"><SectionHeading action={<Badge tone="purple">Simulated evaluation</Badge>}>Your {program.name} evaluation</SectionHeading><div className="checkout-account"><div><span>Starting balance</span><strong>{money(program.size, 0)}</strong></div><img src="/brand/symbol.svg" alt="" /></div><div className="checkout-key-rules"><div><span>Profit target</span><strong>8%</strong></div><div><span>Maximum drawdown</span><strong>5%</strong></div><div><span>Time limit</span><strong>None</strong></div></div><Notice>Evaluation profits are simulated and cannot be withdrawn. Passing unlocks the funded activation stage.</Notice><h3>Payment details</h3><DataRow label="Network" value="Solana" /><DataRow label="Currency" value="USDC" /><DataRow label="From" value={session.status === 'signed-in' ? `${session.walletName} · ${shortAddress(session.me.wallet)}` : 'No wallet connected'} /><DataRow label="To" value="Props.trade · sample fee recipient" /><DataRow label="Terms" value="Illustrative program · v0.1" /></section><aside className="surface checkout-total"><h2>Payment summary</h2><FeeSummary />{covered && <div className="balance-check"><Check size={14} /><span>Your USDC balance covers this payment</span></div>}<label className="checkout-agreement"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} /><span>I understand the evaluation rules and that this is a simulated design preview.</span></label><Button className="full-width" disabled={!accepted || busy} icon={ArrowRight} onClick={pay}>{busy ? 'Preparing preview…' : `Simulate ${number(program.fee + .02)} USDC payment`}</Button><p className="sheet-footnote">No real USDC will leave your wallet.</p><div className="payment-method"><UsdcIcon /><span>USDC</span><span className="quiet">on Solana</span><ShieldCheck size={17} /></div></aside></div></div>;
}

export function PaymentPage() {
  const { program, navigate, setStage, setEvaluationSize } = useApp();
  const [status, setStatus] = useState(() => sessionStorage.getItem('props.payment') === 'pending' ? 0 : 3);
  useEffect(() => { if (status !== 0) return; const a = setTimeout(() => setStatus(1), 500); const b = setTimeout(() => setStatus(2), 1100); const c = setTimeout(() => { setStatus(3); sessionStorage.removeItem('props.payment'); }, 1850); return () => { clearTimeout(a); clearTimeout(b); clearTimeout(c); }; }, []);
  const complete = status === 3;
  return <div className="page outcome-page"><div className="outcome-layout"><section className="outcome-main"><div className={`outcome-symbol ${complete ? 'success' : ''}`}>{complete ? <CheckCheck size={31} /> : <Clock3 size={31} />}</div><Badge tone={complete ? 'green' : 'purple'}>{complete ? 'Payment complete · Preview' : 'Payment processing · Preview'}</Badge><h1>{complete ? 'Your next chapter is ready.' : 'Getting your account ready.'}</h1><p>{complete ? 'Your evaluation is active. Take a breath, find your market, and trade your process.' : 'Confirmation and account activation are separate steps. You can follow both here.'}</p><div className="activation-timeline">{[['Payment submitted', `${number(program.fee + .02)} USDC · Sample transaction`], ['Payment confirmed', 'Evaluation payment recorded'], ['Account activated', `${program.name} evaluation is ready`]].map(([title, detail], i) => <div key={title} className={status > i ? 'done' : status === i ? 'current' : ''}><span>{status > i ? <Check size={15} /> : i + 1}</span><div><strong>{title}</strong><small>{detail}</small></div>{status > i && <Badge tone="green">Complete</Badge>}</div>)}</div><Button disabled={!complete} icon={ArrowRight} onClick={() => { setEvaluationSize(program.size); setStage('evaluation'); navigate('/trade/evaluation'); }}>Open your evaluation</Button><a href="#/account/evaluation" className="text-button">View account overview <ArrowUpRight size={14} /></a></section><aside className="receipt-sheet"><div className="receipt-top"><span>Evaluation receipt</span><img src="/brand/symbol.svg" alt="" /></div><h2>{program.name} account</h2><p>PT-003192</p><RuleList size={program.size} /><FeeSummary /><div className="receipt-footer"><FileCheck2 size={15} /><span>Sample receipt · No onchain payment</span></div></aside></div></div>;
}

export function ResultPage() {
  const { navigate, evaluationSize } = useApp();
  const [result, setResult] = useState('passed');
  const passed = result === 'passed', checking = result === 'checking';
  return <div className="page outcome-page"><div className="preview-state-control"><label>Preview result <select value={result} onChange={e => setResult(e.target.value)}><option value="passed">Passed</option><option value="checking">Still checking</option><option value="breached">Rule breached</option></select></label></div><div className="outcome-layout"><section className="outcome-main"><div className={`outcome-symbol ${passed ? 'success' : checking ? '' : 'error'}`}>{passed ? <ShieldCheck size={32} /> : checking ? <Clock3 size={32} /> : <Info size={32} />}</div><Badge tone={passed ? 'green' : checking ? 'amber' : 'red'}>{passed ? 'Evaluation passed' : checking ? 'Result under review' : 'Evaluation ended'}</Badge><h1>{passed ? <>You brought the edge.<br />Let's bring the capital.</> : checking ? 'One final check.' : 'A clear result. A fresh start.'}</h1><p>{passed ? 'Your sample evaluation met its objectives. The next step is activating your funded account.' : checking ? 'Your target has been reached. Positions, fees and account rules are being reconciled before the result is final.' : 'This example account crossed its static equity floor. Your trade history stays available so you can review what happened.'}</p><div className="result-metrics"><div><span>Final equity</span><strong>{money(evaluationSize * (passed || checking ? 1.08258 : .948568))}</strong></div><div><span>{passed || checking ? 'Qualifying profit' : 'Equity floor'}</span><strong className={passed || checking ? 'positive' : ''}>{passed || checking ? `+${money(evaluationSize * .08258)}` : money(evaluationSize * .95)}</strong></div></div><Button disabled={checking} icon={ArrowRight} onClick={() => navigate(passed ? '/activate' : '/get-funded')}>{passed ? 'Continue to funded activation' : checking ? 'Waiting for final result' : 'Explore another evaluation'}</Button><a href="#/activity" className="text-button">Review account history <ArrowUpRight size={14} /></a></section><aside className="surface result-checklist"><h2>{passed ? 'Every objective, accounted for.' : 'Account checks'}</h2>{[['Profit target', `${money(evaluationSize * .08258)} / ${money(evaluationSize * .08)}`, passed || checking], ['Drawdown rule', passed || checking ? `Equity stayed above ${money(evaluationSize * .95)}` : `Floor crossed by ${money(evaluationSize * .001432)}`, passed || checking], ['Account reconciliation', checking ? 'Positions and fees are being checked' : 'All sample records reconciled', !checking]].map(([title, detail, ok]) => <div className="result-check" key={title}><span className={ok ? 'checkmark' : 'pending-mark'}>{ok ? <Check size={15} /> : <Clock3 size={15} />}</span><span><strong>{title}</strong><small>{detail}</small></span></div>)}<Notice>Evaluation profits do not transfer to the funded account. Funded trading starts with its own allocation and rules.</Notice><InlineLink href="#/verify">Inspect the sample account record</InlineLink></aside></div></div>;
}

export function ActivationPage() {
  const { navigate, setStage, evaluationSize, setFundedSize } = useApp();
  const [status, setStatus] = useState('ready');
  const [busy, setBusy] = useState(false);
  return <div className="page activation-page"><PageHeading title="Make room for your next chapter." description="Review what changes when you step into a funded account." back={{ label: 'Evaluation result', href: '#/result' }}><div className="preview-state-control"><label>Preview state <select value={status} onChange={e => setStatus(e.target.value)}><option value="ready">Capital available</option><option value="queued">Awaiting capital</option></select></label></div></PageHeading><div className="activation-layout"><section className="surface activation-allocation"><span className="account-emblem"><ShieldCheck size={25} /></span><h2>Your funded allocation</h2><strong className="allocation-value">{money(evaluationSize, 0)}<span>USDC</span></strong><Badge tone={status === 'ready' ? 'green' : 'amber'} dot>{status === 'ready' ? 'Ready to activate · Preview' : 'Awaiting allocation · Preview'}</Badge><div className="allocation-details"><DataRow label="Account" value="PT-002841" /><DataRow label="Capital source" value="Props.trade vault" /><DataRow label="Proposed execution" value="GMTrade" /><DataRow label="Your share of eligible profits" value="80%" /><DataRow label="Equity floor" value={money(evaluationSize * .95)} /></div><Button className="full-width" disabled={busy || status === 'queued'} icon={ArrowRight} onClick={() => { setBusy(true); setTimeout(() => { setFundedSize(evaluationSize); setStage('funded'); navigate('/account/funded'); }, 800); }}>{status === 'queued' ? 'Waiting for capital' : busy ? 'Activating preview…' : 'Activate funded preview'}</Button><p className="sheet-footnote">{status === 'queued' ? 'No estimated activation time is available yet.' : 'This action uses example data and sends no transaction.'}</p></section><section className="activation-changes"><h2>Same workspace.<br />A new stage.</h2><div className="change-row"><span><TrendingIcon /></span><div><h3>From simulated to funded</h3><p>The live product is intended to route funded trades to GMTrade using allocated vault margin.</p></div></div><div className="change-row"><span><Wallet size={21} /></span><div><h3>Profits become eligible for payout</h3><p>Settled profits follow your funded account's payout rules and profit split.</p></div></div><div className="change-row"><span><ShieldCheck size={21} /></span><div><h3>Your risk limits stay visible</h3><p>You can trade the allocation. Vault principal remains separate from withdrawable profits.</p></div></div><Notice>Real activation depends on supported permissions, capital availability and confirmed transactions.</Notice></section></div></div>;
}
function TrendingIcon() { return <ArrowUpRight size={22} />; }
